config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users do
      member do
        get :toggle_admin
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5

  before_destroy :last_admin
  before_update :last_admin, if: :admin_changed?
  # before_validation { email.downcase! }
  has_many :tasks, dependent: :destroy
  has_secure_password
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :update, if: :password_digest_changed?

  private

  def last_admin
    throw(:abort) if User.where(admin:true).where.not(id: self.id).count == 0
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :toggle_admin, :destroy]
  before_action :admin_user

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを作成しました"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを更新しました"
    else
      render :edit
    end
  end

  def toggle_admin
    if current_user == @user
      if rollback?
        redirect_to admin_users_path
        flash[:notice] = "権限を変更できません"
      else
        redirect_to tasks_path
        current_user.toggle!(:admin)
        flash[:notice] = "管理者権限がなくなりました"
      end
    else
      @user.toggle!(:admin)
      redirect_to admin_users_path
      flash[:notice] = "権限を変更しました"
    end
  end

  def destroy
    if current_user != @user
      @user.destroy
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除しました"
    else
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除できません"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def admin_user
    raise ActionController::RoutingError, "アクセスする許可がありません" unless current_user.admin?
  end

  def rollback?
    User.where(admin:true).where.not(id: current_user.id).count == 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :already_logged_in, only: [:new, :create]
  before_action :unauthorized_user, only: [:show]
  skip_before_action :authenticated_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to tasks_path
      flash[:notice] = "ログインしました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def unauthorized_user
    if current_user != @user && !current_user.admin?
      redirect_to tasks_path
      flash[:notice] = "権限がありません"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="card bg-light mx-auto mt-5" style="max-width: 800px;">
  <div class="card-body mx-auto" style="min-width: 600px;">
    <h4 class="card-title my-4 text-center"><%= t('view.new_account')%></h4>
      <%=form_with(model: @user, local: true) do |f|%>
        <%= render 'shared/user_error'%>
        <div class="form-group input-group">
          <div class="input-group-prepend">
              <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
          <%= f.label :name, class:"sr-only"%>
          <%= f.text_field :name, class:"form-control", placeholder: t('view.name')%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
        </div>
        <%= f.label :email, class:"sr-only"%>
        <%= f.email_field :email, class:"form-control", placeholder: t('view.email')%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
        </div>
        <%= f.label :password, class:"sr-only"%>
        <%= f.password_field :password, class:"form-control", placeholder:t('view.password')%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <%= f.label :password_confirmation, class:"sr-only"%>
          <%= f.password_field :password_confirmation, class:"form-control", placeholder: t('view.password_confirmation')%>
        </div>

        <div class="form-group">
          <%= f.submit t('view.sign_up'), class:"btn btn-info btn-block"%>
        </div>

        <p class="text-center"><%= t('message.existing_account')%><%= link_to t('view.login'), new_session_path %> </p>
      <%end%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card mt-5">
  <div class="card-body">
    <div class="my-4 text-center">
      <span class="h3 ml-5 mr-3 mb-0 text-dark"><%= @user.name %></span>
    </div>
    <hr>
    <div class="my-auto text-center">
      <p class="h4 my-3"><%=t('show.task_total')%> <%= @user.tasks.count%> <%=t('show.unit')%></P>
      <p class="h5"><%=t('show.not_started')%>：<%= @user.tasks.where(status: "not_started").count%> <%=t('show.unit')%></P>
      <p class="h5"><%=t('show.in_progress')%>：<%= @user.tasks.where(status: "in_progress").count%> <%=t('show.unit')%></P>
      <p class="h5"><%=t('show.finished')%>：<%= @user.tasks.where(status: "finished").count%> <%=t('show.unit')%></P>
      <%= link_to t('show.to_all_tasks'), tasks_path, class: "btn btn-outline-info far fa-file-alt mt-5"%></p>
    </div>
  </div>
</div>