config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users do
      member do
        get :toggle_admin
      end
    end
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <% if logged_in? && current_user.admin? %>
    <a class="navbar-brand font-weight-bold mr-4">Yoho Task
    <small class="ml-2"><%=t('view.admin')%></small></a>
  <% else %>
    <a class="navbar-brand font-weight-bold mr-4">Yoho Task</a>
  <% end %>
  <% if logged_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav justify-content-center">
        <li class="nav-item">
          <%= link_to t('index.page_title'), tasks_path, class: "nav-link #{ "active" if current_page?(tasks_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to t('view.my_page'), user_path(current_user.id), class: "nav-link #{ "active" if current_page?(user_path(current_user.id))}" %>
        </li>
      <% if logged_in? && current_user.admin? %>
       <li class="nav-item">
          <%= link_to t('view.user_management'), admin_users_path, class: "nav-link #{ "active" if current_page?(admin_users_path)}" %>
        </li>
      <% end %>
      </ul>
      <ul class="nav navbar-nav ml-auto justify-content-end">
          <li class="nav-item">
            <%= link_to t('view.logout'), session_path(current_user.id), method: :delete, class: "nav-link"%>
          </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/shared/_user_error.html.erb
<div class="error-container">
  <% if @user.errors.any? %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="text-left">
        <p><strong><%= t('message.user_input_error')%></strong></p>
        <% @user.errors.full_messages.each do |message| %>
          <p><i class="fas fa-exclamation-triangle"></i> <%=message%></p>
        <%end%>
      </div>
    </div>
  <%end%>
</div>