config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users do
      member do
        get :toggle_admin
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5

  before_destroy :last_admin
  before_update :last_admin, if: :admin_changed?
  # before_validation { email.downcase! }
  has_many :tasks, dependent: :destroy
  has_secure_password
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :update, if: :password_digest_changed?

  private

  def last_admin
    throw(:abort) if User.where(admin:true).where.not(id: self.id).count == 0
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :toggle_admin, :destroy]
  before_action :admin_user

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを作成しました"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを更新しました"
    else
      render :edit
    end
  end

  def toggle_admin
    if current_user == @user
      if rollback?
        redirect_to admin_users_path
        flash[:notice] = "権限を変更できません"
      else
        redirect_to tasks_path
        current_user.toggle!(:admin)
        flash[:notice] = "管理者権限がなくなりました"
      end
    else
      @user.toggle!(:admin)
      redirect_to admin_users_path
      flash[:notice] = "権限を変更しました"
    end
  end

  def destroy
    if current_user != @user
      @user.destroy
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除しました"
    else
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除できません"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def admin_user
    raise ActionController::RoutingError, "アクセスする許可がありません" unless current_user.admin?
  end

  def rollback?
    User.where(admin:true).where.not(id: current_user.id).count == 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :already_logged_in, only: [:new, :create]
  before_action :unauthorized_user, only: [:show]
  skip_before_action :authenticated_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to tasks_path
      flash[:notice] = "ログインしました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def unauthorized_user
    if current_user != @user && !current_user.admin?
      redirect_to tasks_path
      flash[:notice] = "権限がありません"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="card bg-light mx-auto mt-5" style="max-width: 800px;">
  <div class="card-body mx-auto" style="min-width: 600px;">
    <h4 class="card-title my-4 text-center"><%=t('admin.edit_user')%></h4>
      <%=form_with(model: [:admin, @user], local: true) do |f|%>
        <%= render 'shared/user_error'%>
        <div class="form-group input-group">
          <div class="input-group-prepend">
              <span class="input-group-text"> <i class="fa fa-user"> <%=t('view.name')%></i></span>
          </div>
          <%= f.label :name, class:"sr-only"%>
          <%= f.text_field :name, class:"form-control"%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-envelope"> <%=t('view.email')%></i></span>
        </div>
        <%= f.label :email, class:"sr-only"%>
        <%= f.email_field :email, class:"form-control"%>
        </div>

        <div class="form-group">
          <%= f.submit t('admin.update'), class:"btn btn-info btn-block"%>
        </div>

      <%end%>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="title text-center">
  <p class="h3 my-4"><%=t('admin.user_index')%></p>
  <%=link_to t('admin.create_user'), new_admin_user_path, class:"btn btn-outline-info fas fa-plus ml-3" %>
</div>

<div class="mt-5 mb-3">
  <%= paginate @users %>
</div>

<table class="table my-2">
  <thead class="text-center">
    <tr>
      <th scope="col"><%=t('admin.user')%></th>
      <th scope="col"><%=t('view.email')%></th>
      <th scope="col" colspan="2"><%=t('admin.task_num')%></th>
      <th scope="col"><%=t('admin.admin_manage')%></th>
      <th scope="col"><%=t('index.task_management')%></th>
    </tr>
  </thead>
  <% @users.each.with_index(1) do |user, index| %>
    <tbody class="h6">
      <tr class="text-center">
        <td><%=user.name%></td>
        <td><%=user.email%></td>
        <td class="text-right"><%=user.tasks.count%></td>
        <td>
          <button class="btn btn-outline-info" id="list_<%=index%>" type="button" data-toggle="collapse" data-target="#list_<%=index%>" aria-expanded="false" aria-controls="list_<%=index%>"><%=t('admin.list')%></button>
        </td>
        <td class="text-center">
          <div>
            <% if user.admin %>
              <%= link_to "", toggle_admin_admin_user_path(user.id), class:"fas fa-toggle-on card-link h3 text-info", id:"admin_#{index}"%>
            <% else %>
              <%= link_to "", toggle_admin_admin_user_path(user.id), class:"fas fa-toggle-off card-link h3 text-info", id:"admin_#{index}"%>
            <% end %>
          </div>
        </td>
        <td>
          <%=link_to t('view.edit'), edit_admin_user_path(user), class:"btn btn-info", id:"edit_#{index}"%>
          <%=link_to t('view.delete'), admin_user_path(user), method: :delete, data: {confirm: t('view.delete_confirm')}, class:"btn btn-danger", id:"dlt_#{index}"%>
        </td>
      </tr>
      <tr>
        <td colspan="6" class="collapse" id="list_<%=index%>">
          <table class="table">
            <thead class="text-center">
              <tr>
                <th scope="col"><%=t('view.task_title')%></th>
                <th scope="col"><%=t('view.deadline')%></th>
                <th scope="col"><%=t('view.status')%></th>
                <th scope="col"><%=t('view.priority')%></th>
                <th scope="col"><%=t('index.task_management')%></th>
              </tr>
            </thead>
            <% user.tasks.each do |task| %>
              <tbody>
                <tr class="text-center">
                  <td><%=task.title%></td>
                  <td><%=task.deadline.strftime(("%Y年%m月%d日 %H時%M分"))%></td>
                  <td><%=Task.statuses_i18n[task.status]%></td>
                  <td><%=Task.priorities_i18n[task.priority]%></td>
                  <td>
                    <%=link_to t('index.detail'), task_path(task), class:"btn btn-info" %>
                  </td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<div class="card bg-light mx-auto mt-5" style="max-width: 800px;">
  <div class="card-body mx-auto" style="min-width: 600px;">
    <h4 class="card-title my-4 text-center"><%=t('admin.create_user')%></h4>
      <%=form_with(model: [:admin, @user], local: true) do |f|%>
        <%= render 'shared/user_error'%>
        <div class="form-group input-group">
          <div class="input-group-prepend">
              <span class="input-group-text"><i class="fa fa-user"> <%=t('view.name')%></i></span>
          </div>
          <%= f.label :name, class:"sr-only"%>
          <%= f.text_field :name, class:"form-control"%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-envelope"> <%=t('view.email')%></i></span>
          </div>
          <%= f.label :email, class:"sr-only"%>
          <%= f.email_field :email, class:"form-control"%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-lock"> <%=t('view.password')%></i></span>
        </div>
        <%= f.label :password, class:"sr-only"%>
        <%= f.password_field :password, class:"form-control"%>
        </div>

        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-lock"> <%=t('view.password_confirmation')%></i></span>
          </div>
          <%= f.label :password_confirmation, class:"sr-only"%>
          <%= f.password_field :password_confirmation, class:"form-control"%>
        </div>


    <div class="my-3">
    </div>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-crown"> <%=t('admin.admin_manage')%></i></span>
          </div>
          <%= f.label :admin, class:"sr-only"%>
          <%= f.select :admin, [[t('admin.yes_admin'), true], [t('admin.no_admin'), false]], class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit t('admin.create'), class:"btn btn-info btn-block"%>
        </div>
      <%end%>
    </div>
  </div>
</div>